### ISSUE TITLE
"Schema validation failed" upon running `ng serve --open`

### ISSUE THREAD

**Issue by leopignataro** [dynamsoft-dwt/angular-cli-application#5]
Dear Dynamsoft team,

I cannot run this sample. I followed the instructions on the *README.md* file, but upon running `ng serve --open`, I get the following error:

```plaintext
PS C:\Temp\WebTwain\angular-cli-application-master> ng serve --open
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:210:42)
    at MergeMapSubscriber._tryNext (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MapSubscriber._next (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:77:26)
```

**Comment by Tom-Dynamsoft** [comment]
Dear leopignataro,

For that error, please refer to
https://stackoverflow.com/questions/56542518/schema-validation-failed-with-the-following-errors-data-path-buildersapp-sh/56624167

Note that the sample angular-cli-application has the following
    "@angular-devkit/build-angular": "~0.801.0",

while "Scan-Documents-with-Angular" is like this
    "@angular-devkit/build-angular": "~0.13.0",
